/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms.ui;

import javax.swing.table.DefaultTableModel;
import tms.manager.UserProfileManager;
import tms.model.User;

/**
 *
 * @author 3mora
 */
public class UsersWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UsersWindow.class.getName());
    private DefaultTableModel tableModel;
    private UserProfileManager userManager;
    private static UsersWindow instance=null;
    /**
     * Creates new form UsersWindow
     */
    private UsersWindow() {
        initComponents();
        setLocationRelativeTo(null);
        
        userManager = UserProfileManager.getInstance();
        setupTable();
        loadUsers();
        setResizable(false);
    }public static UsersWindow getInstance(){
        if (instance==null){
            instance=new UsersWindow();
        }
        return instance;
    }
    
    @Override 
    public void setVisible(boolean visible){
        if (visible){
            loadUsers();
        }
        super.setVisible(visible);
        if(visible){
            toFront();
            requestFocus();
        }
    }
    
    private void setupTable(){
        String[] columns={"Id","Name","Email","Loyalty Points"};
        tableModel = new DefaultTableModel(columns,0){
            @Override
            public boolean isCellEditable(int raw,int column){
                return false;
            }
        };
        tblUsers.setModel(tableModel);
    }
    
    private void loadUsers(){
        tableModel.setRowCount(0);
        for(User user :userManager.getUsers()){
            tableModel.addRow(new Object[]{
                user.getId(),
                user.getName(),
                user.getEmail(),
                user.getLoyalPoints()
        });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnAddUser = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAddPoints = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(this::btnAddUserActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnAddPoints.setText("Add Points");
        btnAddPoints.addActionListener(this::btnAddPointsActionPerformed);

        btnClose.setBackground(new java.awt.Color(223, 71, 89));
        btnClose.setText("Close");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Users Management");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnAddPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPointsActionPerformed
        // TODO add your handling code here:
        int selectedRow=tblUsers.getSelectedRow();
        if (selectedRow==-1){
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a User");
        }
        int userId = (int)tableModel.getValueAt(selectedRow, 0);
        String pointStr = javax.swing.JOptionPane.showInputDialog(this,
                "Enter points to add : ");
        if(pointStr!=null&& !pointStr.trim().isEmpty()){
            try {
                int points = Integer.parseInt(pointStr.trim());
                userManager.addPointsToUser(userId, points);
                loadUsers();
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Points Added successfully ");
            } catch (NumberFormatException e) {
                                javax.swing.JOptionPane.showMessageDialog(this,
                        "Invalid Points");
            }
        }
    }//GEN-LAST:event_btnAddPointsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow=tblUsers.getSelectedRow();
        if (selectedRow==-1){
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a User");
        }
        int userId = (int)tableModel.getValueAt(selectedRow, 0);
        String userName = (String)tableModel.getValueAt(selectedRow, 1);
                    
        int confirm= javax.swing.JOptionPane.showConfirmDialog(this, 
                "Delete user '"+userName+"' ?",
                "Confirm Delete",
                javax.swing.JOptionPane.YES_NO_OPTION
                );
        
                if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                    if (userManager.deleteUser(userId)) {
                        loadUsers();
                        javax.swing.JOptionPane.showMessageDialog(this,
                                "User '"+ userName +"' deleted successfully.");
                    }

                }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        javax.swing.JTextField txtId =new javax.swing.JTextField();
        javax.swing.JTextField txtName =new javax.swing.JTextField();
        javax.swing.JTextField txtEmail =new javax.swing.JTextField();
        
        javax.swing.JPanel panel= new javax.swing.JPanel(new java.awt.GridLayout(3,2,5,5));
        
        panel.add(new javax.swing.JLabel("ID :"));
        panel.add(txtId);
        panel.add(new javax.swing.JLabel("Name :"));
        panel.add(txtName);
        panel.add(new javax.swing.JLabel("Email :"));
        panel.add(txtEmail);
        
        int result = javax.swing.JOptionPane.showConfirmDialog(this, panel
        ,"Add New User", javax.swing.JOptionPane.OK_CANCEL_OPTION);
        if (result== javax.swing.JOptionPane.OK_OPTION){
            try {
                int id= Integer.parseInt(txtId.getText().trim());
                String name= txtName.getText().trim();
                String email= txtEmail.getText().trim();
                if (name.isEmpty()||email.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "All field are required!!.... please make sure you fill them");
                    return;
                }
                User user =new User(id,name,email);
                User added =userManager.addUser(user);
                
                if(added!=null){
                    loadUsers();
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "You Added user "+ added.getName()+" successfully!");
                }else{
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Failde to add User");
                }
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Invalid Id");
            }
        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UsersWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPoints;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
